In [1]:
import fitz

pdf = fitz.open("../Stock Trader's Almanac 2026_L.pdf")

print("Pages:", len(pdf))

Pages: 273

In [2]:
for page_num in range(len(pdf)):

    text = pdf[page_num].get_text()

    if "MAY ALMANAC" in text:
        print("Found on page:", page_num + 1)

Found on page: 2
Found on page: 65

In [3]:
for page_num in range(64, 70):

    print("\n")
    print("=" * 80)
    print("PAGE", page_num + 1)
    print("=" * 80)

    text = pdf[page_num].get_text()

    print(text[:5000])

================================================================================
PAGE 65
================================================================================
MAY ALMANAC
Market Probability Chart above is a graphic representation of the S&P 500 Recent
Market Probability Calendar on page 126.
◆ “May/June disaster area” between 1965 and 1984 with S&P down 15 out of 20
Mays ◆ Between 1985 and 1997 May was the best month with 13 straight gains,
gaining 3.3% per year on average, up 19, down 9 since ◆ Worst six months of the year
begin with May (page 54) ◆ A $10,000 investment compounded to $1,316,635 gain
for November-April in 75 years compared to a $4,253 gain for May-October ◆ Dow
Memorial Day week record: up 12 years in a row (1984-1995), down 17 of the last 30
years ◆ Since 1950 midterm election year Mays rank, #8 Dow, #9 S&P and #6
NASDAQ
May Vital Statistics
DJIA
S&P 500
NASDAQ
Russell 1K Russell 2K
Rank
9
8
5
6
4
Up
41
46
33
32
29
Down
34
29
21
14
17
Average % Change
–0.02
0.3
1.1
0.9
1.3
Midterm Yr Avg %
Chg
–0.6
–0.7
–0.8
0.1
–1.0
Best & Worst May
% Change
% Change
% Change
% Change
% Change
Best
1990 8.3
1990 9.2
1997
11.1
1990 8.9
1997 11.0
Worst
2010
–
7.9
1962
–
8.6
2000
–
11.9
2010
–
8.1
2019
–
7.9
Best & Worst May Weeks
Best
5/27/22 6.2 5/27/22 6.6 5/17/02
8.8 5/27/22 6.6 5/22/20 7.8
Worst
5/25/62
–
6.0
5/25/62
–
6.8
5/7/10
–
8.0
5/7/10
–
6.6
5/7/10
–
8.9
Best & Worst May Days



================================================================================
PAGE 66
================================================================================
Best
5/27/70
5.1 5/27/70 5.0 5/30/00
7.9 5/10/10 4.4 5/18/20 6.1
Worst
5/28/62
–
5.7
5/28/62
–
6.7
5/23/00 –5.9 5/18/22
–
4.0
5/20/10
–
5.1
First Trading Day of Monthly Expiration Week: 1980–2025
Record (#Up–
#Down)
27–18
28–17
25–20
26–19
23–22
Current streak
D1
D1
U2
D1
U2
Avg % Change
0.10
0.10
0.08
0.07
–0.04
Monthly Options Expiration Day: 1980–2025
Record (#Up–
#Down)
24–21
25–20
20–25
25–20
22–23
Current streak
U1
U1
D4
U1
D3
Avg % Change
–0.05
–0.07
–0.10
–0.06
0.03
Monthly Options Expiration Week: 1980–2025
Record (#Up–
#Down)
21–24
21–24
23–22
20–25
23–22
Current streak
U2
U2
U2
U2
U2
Avg % Change
–0.08
–0.06
0.12
–0.06
–0.22
Week After Monthly Options Expiration: 1980–2025
Record (#Up–
#Down)
25–20
30–15
32–13
29–16
32–13
Current streak
D2
U5
U5
D1
D2
Avg % Change
0.19
0.40
0.59
0.42
0.65
First Trading Day Performance
% of Time Up
56.6
57.9
60.0
57.4
63.8
Avg % Change
0.16
0.19
0.28
0.18
0.19
Last Trading Day Performance
% of Time Up
56.0
58.7
61.1
52.2
56.5
Avg % Change
0.13
0.20
0.14
0.13
0.17
Dow & S&P 1950–May 2, 2025; NASDAQ 1971–May 2, 2025; Russell 1K & 2K 1979–May
2, 2025.
Better to reposition in May Than to sell in May and go away.
APRIL/MAY 2026
Whenever a well-known bearish analyst is interviewed [Cover story] in the
financial press, it usually coincides with an important near-term market
bottom.
— Clif Droke (Clifdroke.com, 11/15/04)



================================================================================
PAGE 67
================================================================================
I’ve never been poor, only broke. Being poor is a frame of mind. Being broke is only a
temporary situation.
— Mike Todd (Movie Producer, 1903–1958)
FOMC Meeting
No horse gets anywhere until he is harnessed. No steam or gas ever drives anything
until it is confined. No Niagara is ever turned into light and power until it is tunneled.
No life ever grows great until it is focused, dedicated, disciplined.
— Harry Emerson Fosdick (Protestant minister, author, 1878–1969)
There is no tool to change human nature…people are prone to recurring bouts of
optimism and pessimism that manifest themselves from time to time in the buildup or
cessation of speculative excesses.
— Alan Greenspan (Fed Chairman 1987–2006, July 18, 2001 monetary policy report to
the Congress)
First Trading Day in May, S&P Up 19 of Last 28
Government is like fire—useful when used legitimately, but dangerous when not.
— David Brooks (NY Times columnist, 10/5/07)
SUMMER MARKET VOLUME DOLDRUMS DRIVE WORST SIX MONTHS
In recent years, Memorial Day weekend has become the unofficial start of summer. Not
long afterwards, trading activity typically begins to slowly decline (barring any external
event triggers) towards a later summer low. We refer to this summertime slowdown in
trading as the doldrums due to the anemic volume and uninspired trading on Wall Street.
The individual trader, if they are looking to sell a stock, is generally met with disinterest
from The Street. It becomes difficult to sell a stock at a good price. That is also why many
summer rallies tend to be short lived and are quickly followed by a pullback or correction.



================================================================================
PAGE 68
================================================================================
Above are plotted the one-year seasonal volume patterns since 1965 for the NYSE and
since 1978 for NASDAQ against the annual average daily volume moving average for 2025
as of the close on May 9, 2025. The typical summer lull is highlighted in blue. A prolonged
surge in volume during the typically quiet summer months, especially when accompanied
by gains, can be an encouraging sign that the bull market will continue. However, should
traders lose their conviction and participate in the annual summer exodus from The
Street, a market pullback or correction could quickly unfold.
MAY 2026
What is conservatism? Is it not adherence to the old and tried, against the new and



================================================================================
PAGE 69
================================================================================
untried?
— Abraham Lincoln (16th U.S. President, 1809–1865)
If you’re wrong, you can just change your mind. It’s not that big of a deal. You don’t
have to live this depressing life of trend fighting. That’s no good.
— J. C. Parets, CMT (Founder All Star Charts, Stock Market Media and TrendLabs, b.
1982)
A market is the combined behavior of thousands of people responding to information,
misinformation and whim.
— Kenneth Chang (NY Times journalist)
Only those who will risk going too far can possibly find out how far one can go.
— T.S. Eliot (English poet, essayist and critic, The Wasteland, 1888–1965)
Friday Before Mother’s Day, Dow Up 20 of Last 31
Under capitalism, the seller chases after the buyer, and that makes both of them work
better; under socialism, the buyer chases the seller, and neither has time to work.
— Andrei Sakharov’s Uncle Ivan
Mother’s Day
TOP-PERFORMING MONTHS: STANDARD & POOR’S 500 AND DOW JONES
INDUSTRIALS
Monthly performance of the S&P and the Dow are ranked over the past 75 1/3 years.
NASDAQ monthly performance is shown on page 60.
April, November, and December still hold the top three positions in both the Dow and
S&P. Disastrous Januarys in 2008, 2009, 2016, and 2022 knocked January into fifth.
This, in part, led to our discovery in 1986 of the market’s most consistent seasonal pattern.
You can divide the year into two sections and have practically all the gains in one six-
month section and very little in the other. September is the worst month on both lists. (See
“Best Six Months” on page 54.)
MONTHLY % CHANGES (JANUARY 1950–APRIL 2025)



================================================================================
PAGE 70
================================================================================
Standard & Poor’s 500
Dow Jones Industrials
Total % Avg. %
#
#
Total % Avg. %
#
#
Month
Change Change Up Down Month Change Change Up Down
Jan
82.0%
1.1% 46
30
Jan
73.6%
1.0% 48
28
Feb
–1.8
–0.02 41
35
Feb
4.3
0.1 44
32
Mar
78.6
1.0 49
27
Mar
68.3
0.9 49
27
Apr
109.5
1.4 53
23
Apr
134.9
1.8 51
25
May
21.3
0.3 46
29
May
– 1.8
– 0.02 41
34
Jun
11.4
0.2 42
33
Jun
–12.3
–0.2 36
39
Jul
96.0
1.3 45
30
Jul
105.0
1.4 50
25
Aug
1.4
0.02 41
34
Aug
–7.3
–0.1 42
33
Sep*
–51.2
–0.7 33
41
Sep
–61.8
–0.8 30
45
Oct
66.6
0.9 44
31
Oct
54.6
0.7 44
31
Nov
140.4
1.9 52
23
Nov
143.8
1.9 52
23
Dec
107.3
1.4 55
20
Dec
109.9
1.5 52
23
%
%
Rank
Rank
Nov
140.4%
1.9% 52
23
Nov 143.8%
1.9% 52
23
Apr
109.5
1.4 53
23
Apr
134.9
1.8 51
25
Dec
107.3
1.4 55
20
Dec
109.9
1.5 52
23
Jul
96.0
1.3 45
30
Jul
105.0
1.4 50
25
Jan
82.0
1.1 46
30
Jan
73.6
1.0 48
28
Mar
78.6
1.0 49
27
Mar
68.3
0.9 49
27
Oct
66.6
0.9 44
31
Oct
54.6
0.7 44
31
May
21.3
0.3 46
29
Feb
4.3
0.1 44
32
Jun
11.4
0.2 42
33
May
–1.8
–0.02 41
34
Aug
1.4
0.02 41
34
Aug
–7.3
–0.1 42
33
Feb
–1.8
–0.02 41
35
Jun
–12.3
–0.2 36
39
Sep*
–51.2
–0.7 33
41
Sep
–61.8
–0.8 30
45
Totals
661.5%
8.8%
Totals
611.2%
8.2%
Average
0.73%
Average
0.68%
*No change 1979
Anticipators, shifts in cultural behavior and faster information flow have altered
seasonality in recent years. Here is how the months ranked over the past 15 1/3 years (185
months) using total percentage gains on the S&P 500: November 46.4, July 43.0, October
31.9, April 17.9, February 15.8, Janaury 15.4, March 13.3, December 8.9, June 8.7, May –
2.4, August –6.6, and September –14.2.
January has declined in 13 of the last 26 years. Sizeable turnarounds in “bear killing”
October were a common occurrence from 1999 to 2007 and 2022. Recent big Dow losses

In [4]:
page = pdf[64]

pix = page.get_pixmap(
    matrix=fitz.Matrix(3,3)
)

pix.save("may_almanac_page.png")

print("saved")

saved

In [5]:
may_stats = {
    "Month": "May",

    "SP500 Rank": 8,

    "SP500 Up Years": 46,

    "SP500 Down Years": 29,

    "SP500 Average Return": 0.3,

    "SP500 Midterm Year Return": -0.7,

    "Seasonal Bias": "Slightly Bearish"
}

may_stats

{'Month': 'May',
 'SP500 Rank': 8,
 'SP500 Up Years': 46,
 'SP500 Down Years': 29,
 'SP500 Average Return': 0.3,
 'SP500 Midterm Year Return': -0.7,
 'Seasonal Bias': 'Slightly Bearish'}

In [6]:
import pandas as pd

evidence = {
    "Evidence": [
        "May ranks #8 for S&P 500",
        "Average May return is +0.3%",
        "Midterm Year average return is -0.7%",
        "May starts the Worst Six Months"
    ],

    "Impact": [
        "Neutral",
        "Bullish",
        "Bearish",
        "Bearish"
    ]
}

evidence_df = pd.DataFrame(evidence)

evidence_df

                               Evidence   Impact
0              May ranks #8 for S&P 500  Neutral
1           Average May return is +0.3%  Bullish
2  Midterm Year average return is -0.7%  Bearish
3       May starts the Worst Six Months  Bearish

In [7]:
almanac_agent = {
    "Month": "May",

    "Bias": "Slightly Bearish",

    "Confidence": "Medium",

    "Bullish Factors": [
        "Average May return is +0.3%",
        "46 up years vs 29 down years"
    ],

    "Bearish Factors": [
        "Midterm Year average return is -0.7%",
        "May begins the Worst Six Months"
    ]
}

almanac_agent

{'Month': 'May',
 'Bias': 'Slightly Bearish',
 'Confidence': 'Medium',
 'Bullish Factors': ['Average May return is +0.3%',
  '46 up years vs 29 down years'],
 'Bearish Factors': ['Midterm Year average return is -0.7%',
  'May begins the Worst Six Months']}

In [8]:
for page_num in range(len(pdf)):

    text = pdf[page_num].get_text()

    if "Memorial Day" in text:
        print("Found on page:", page_num + 1)
        print("-" * 50)
        print(text[:2000])
        print("\n")

Found on page: 65
--------------------------------------------------
MAY ALMANAC
Market Probability Chart above is a graphic representation of the S&P 500 Recent
Market Probability Calendar on page 126.
◆ “May/June disaster area” between 1965 and 1984 with S&P down 15 out of 20
Mays ◆ Between 1985 and 1997 May was the best month with 13 straight gains,
gaining 3.3% per year on average, up 19, down 9 since ◆ Worst six months of the year
begin with May (page 54) ◆ A $10,000 investment compounded to $1,316,635 gain
for November-April in 75 years compared to a $4,253 gain for May-October ◆ Dow
Memorial Day week record: up 12 years in a row (1984-1995), down 17 of the last 30
years ◆ Since 1950 midterm election year Mays rank, #8 Dow, #9 S&P and #6
NASDAQ
May Vital Statistics
DJIA
S&P 500
NASDAQ
Russell 1K Russell 2K
Rank
9
8
5
6
4
Up
41
46
33
32
29
Down
34
29
21
14
17
Average % Change
–0.02
0.3
1.1
0.9
1.3
Midterm Yr Avg %
Chg
–0.6
–0.7
–0.8
0.1
–1.0
Best & Worst May
% Change
% Change
% Change
% Change
% Change
Best
1990 8.3
1990 9.2
1997
11.1
1990 8.9
1997 11.0
Worst
2010
–
7.9
1962
–
8.6
2000
–
11.9
2010
–
8.1
2019
–
7.9
Best & Worst May Weeks
Best
5/27/22 6.2 5/27/22 6.6 5/17/02
8.8 5/27/22 6.6 5/22/20 7.8
Worst
5/25/62
–
6.0
5/25/62
–
6.8
5/7/10
–
8.0
5/7/10
–
6.6
5/7/10
–
8.9
Best & Worst May Days



Found on page: 67
--------------------------------------------------
I’ve never been poor, only broke. Being poor is a frame of mind. Being broke is only a
temporary situation.
— Mike Todd (Movie Producer, 1903–1958)
FOMC Meeting
No horse gets anywhere until he is harnessed. No steam or gas ever drives anything
until it is confined. No Niagara is ever turned into light and power until it is tunneled.
No life ever grows great until it is focused, dedicated, disciplined.
— Harry Emerson Fosdick (Protestant minister, author, 1878–1969)
There is no tool to change human nature…people are prone to recurring bouts of
optimism and pessimism that manifest themselves from time to time in the buildup or
cessation of speculative excesses.
— Alan Greenspan (Fed Chairman 1987–2006, July 18, 2001 monetary policy report to
the Congress)
First Trading Day in May, S&P Up 19 of Last 28
Government is like fire—useful when used legitimately, but dangerous when not.
— David Brooks (NY Times columnist, 10/5/07)
SUMMER MARKET VOLUME DOLDRUMS DRIVE WORST SIX MONTHS
In recent years, Memorial Day weekend has become the unofficial start of summer. Not
long afterwards, trading activity typically begins to slowly decline (barring any external
event triggers) towards a later summer low. We refer to this summertime slowdown in
trading as the doldrums due to the anemic volume and uninspired trading on Wall Street.
The individual trader, if they are looking to sell a stock, is generally met with disinterest
from The Street. It becomes difficult to sell a stock at a good price. That is also why many
summer rallies tend to be short lived and are quickly followed by a pullback or correction.



Found on page: 75
--------------------------------------------------
invulnerable, whereupon it is ripe for a bust.
— George Soros (Financier, philanthropist, political activist, author and philosopher, b.
1930)
Friday Before Memorial Day Tends to Be Lackluster with Light Trading, Dow
Mixed, Up 13 Down 13, Average –0.05%
Intense concentration hour after hour can bring out resources in people they didn’t know
they had.
— Edwin Land (Polaroid inventor and founder, 1909–1991)
MACD-TIMING TRIPLES BEST-SIX-MONTHS RESULTS
Using the simple MACD (Moving Average Convergence Divergence) indicator developed
by our friend Gerald Appel to better time entries and exits into and out of the Best Six
Months (page 54) period nearly triples the results. Sy Harding enhanced our Best-Six-
Months triggers, dubbing it the “best mechanical system ever.” In 2006 we improved
results with just four trades every four years (page 64).
Our Almanac Investor (see insert) implements this system with quite a degree of success.
Starting on the first trading day of October we look to catch the market’s first hint of an
uptrend after the summer doldrums, and beginning on the first trading day of April we
prepare to exit these seasonal positions as soon as the market falters.
In up-trending markets MACD signals get you in earlier and keep you in longer. But if the
market is trending down, entries are delayed until the market turns up and exit points can
come a month earlier.
The results are astounding applying the simple MACD signals. Instead of $10,000 gaining
$1,316,635 over the 75 recent years when invested only during the Best Six Months (page
54), the gain nearly tripled to $3,743,209. The $4,253 gain during the worst six months
became a loss of $4,931.
Impressive results for being invested during only 6.3 months of the year on average! For
the rest of the year consider money markets, bonds, puts, bear funds, covered calls or
credit call spreads.
Updated signals are emailed to our Almanac Investor subscribers as soon as they are
triggered. Visit www.stocktradersalma


Found on page: 78
--------------------------------------------------
75-Year Gain
(Loss)
($4,931)
( $4,931))
$3,743,209
*MACD generated entry and exit points (earlier or later) can lengthen or shorten six-
month periods.
MAY 2026
Memorial Day (Market Closed)
The soul is dyed the color of its thoughts. Think only on those things that are in line with
your principles and can bear the light of day. The content of your character is your
choice. Day by day, what you do is who you become.
— Heraclitus (Greek philosopher, 535–475 BC)
Day After Memorial Day, Dow Up 23 of Last 39, But Down 8 of Last 10
…the most successful positions I’ve taken have been those about which I’ve been most
nervous (and ignored that emotion anyway). Courage is not about being fearless;
courage is about acting appropriately even when you are fearful.
— Daniel Turov (Turov on Timing, b. 1947)
Memorial Day Week Dow Down 17 of Last 29, Up 12 Straight 1984-1995
If you create an act, you create a habit. If you create a habit, you create a character. If
you create a character, you create a destiny.
— André Maurois (Novelist, biographer, essayist, 1885–1967)
A small debt produces a debtor; a large one, an enemy.
— Publilius Syrus (Syrian-born Roman mime and former slave, 83–43 B.C.)
Start Looking for NASDAQ MACD Sell Signal on June 1 (page 62)
Almanac Investor Subscribers Emailed when It Triggers (See
Insert)
If you want to raise a crop for one year, plant corn. If you want to raise a crop for
decades, plant trees.
If you want to raise a crop for centuries, raise men. If you want to plant a crop for
eternities, raise democracies.
— Carl A. Schenck (German forester, 1868–1955)
June Almanac Investor Sector Seasonalities: See Pages 94, 96, and 98



Found on page: 111
--------------------------------------------------
principle of spending money to be paid by posterity, under the name of funding, is but
swindling futurity on a large scale.
— Thomas Jefferson (3rd U.S. President, 1743–7/4/1826, 1816 letter to John Taylor of
Caroline)
Mid-August Stronger Than Beginning and End
A president is elected and tries to get rid of the dirty stuff in the economy as quickly as
possible, so that by the time the next election comes around, he looks like a hero. The
stock market is reacting to what the politicians are doing.
— Yale Hirsch (Creator of Stock Trader’s Almanac, NY Times 10/10/2010, 1923–2021)
All the features and achievements of modern civilization are, directly or indirectly, the
products of the capitalist process.
— Joseph A. Schumpeter (Austrian-American economist, Theory of Economic
Development, 1883–1950)
MARKET BEHAVIOR THREE DAYS BEFORE AND THREE DAYS AFTER HOLIDAYS
The Stock Trader’s Almanac has tracked holiday seasonality annually since the first
edition in 1968. Stocks used to rise on the day before holidays and sell off the day after,
but nowadays each holiday moves to its own rhythm. Eight holidays are separated into
five groups. Average percent changes for the Dow, S&P 500, NASDAQ, and Russell 2000
are shown.
The Dow and S&P consist of blue chips and the largest cap stocks, whereas NASDAQ
represents tech stocks and the Russell 2000 would be more representative of smaller cap
stocks. This is evident on the last day of the year with NASDAQ and the Russell 2000
having a field day, while their larger brethren in the Dow and S&P are showing losses on
average.
Thanks to the Santa Claus Rally the three days before and after New Year’s Day and
Christmas are best. NASDAQ and the Russell 2000 average gains of 0.9% to 1.5% over the
six-day spans. However, trading around the first day of the year has been mixed recently.
Traders have been selling more the first trading day of the year, pushing gains and losses
into the New Year.
Bullishness before Labor Day and after Memorial Day


Found on page: 112
--------------------------------------------------
Presidents’ Day is the least bullish of all the holidays, bearish the day before and three
days after. NASDAQ has dropped 23 of the last 36 days before Presidents’ Day (Dow, 20 of
36; S&P 22 of 36; Russell 2000, 18 of 36).
HOLIDAYS: 3 DAYS BEFORE, 3 DAYS AFTER (Average % change 1980–April
2025)
–3
–2
–1
+1
+2
+3
S&P 500
– 0.01
0.16 – 0.11
Mixed Before &
0.16
0.22
0.03
DJIA
– 0.01
0.11 – 0.14
Positive After
0.27
0.20
0.15
NASDAQ
0.01
0.21
0.08
New Year’s Day
0.16
0.41
0.10
Russell 2K – 0.05
0.35
0.28
1/1/26
0.01
0.18
0.09
S&P 500
0.35 – 0.01 – 0.11 Negative Before & After
– 0.21 – 0.07 – 0.05
DJIA
0.30 – 0.02 – 0.04
Presidents’
– 0.17 – 0.08 – 0.11
NASDAQ
0.54
0.21 – 0.25
Day
– 0.46 – 0.07
0.03
Russell 2K
0.44
0.18 – 0.04
2/16/26
– 0.39 – 0.17 – 0.02
S&P 500
0.07
0.01
0.37
Positive Before &
– 0.23
0.44
0.09
DJIA
0.05
0.01
0.26
Negative After
– 0.19
0.40
0.09
NASDAQ
0.22
0.19
0.43
Good Friday
– 0.29
0.50
0.18
Russell 2K
0.14
0.16
0.56
4/3/26
– 0.40
0.39
0.05
S&P 500
0.09
0.06
0.11
Positive Before
0.22
0.10
0.25
DJIA
0.05 – 0.02
0.02
& After
0.25
0.10
0.13
NASDAQ
0.18
0.24
0.21
Memorial Day
0.21 – 0.03
0.43
Russell 2K
0.07
0.23
0.23
5/25/26
0.24
0.06
0.38
S&P 500
0.21
0.17
0.13
Positive Before &
– 0.07
0.02
0.09
DJIA
0.18
0.13
0.12
Negative After
– 0.05
0.01
0.06
NASDAQ
0.32
0.19
0.12
Independence Day
– 0.0004 – 0.11
0.27
Russell 2K
0.29
0.04
0.05
7/4/26
– 0.23 – 0.15
0.11
S&P 500
0.21 – 0.21
0.10
Labor Day
– 0.07
0.14 – 0.09
DJIA
0.18 – 0.23
0.10
9/7/26
– 0.06
0.17 – 0.13
NASDAQ
0.39 – 0.07
0.10
– 0.18
0.02
0.03
Russell 2K
0.48
0.02
0.12
– 0.16
0.16
0.001
S&P 500
0.13
0.07
0.24
Positive Before
0.11 – 0.36
0.25
DJIA
0.16
0.07
0.21
& After
0.08 – 0.34
0.25
NASDAQ
0.04 – 0.12
0.40
Thanksgiving
0.33 – 0.32
0.11
Russell 2K
0.22 – 0.03
0.38
11/26/26
0.20 – 0.54
0.19
S&P 500
0.19
0.16
0.18
Christmas
0.29 – 0.03
0.22
DJIA
0.24
0.19
0.19
12/25/26
0.32 0.001
0.18
NASDAQ
– 0.02
0.30
0.34
0.27 – 0.04
0.27
Russell 2K
0.28
0.29
0.32
0.31 – 0.09
0.42

In [9]:
memorial_pages = []

for page_num in range(len(pdf)):

    text = pdf[page_num].get_text()

    if "Memorial Day" in text:
        memorial_pages.append(page_num + 1)

print(memorial_pages)

[65, 67, 75, 78, 111, 112]

In [10]:
keywords = [
    "Memorial Day",
    "Midterm",
    "Worst Six Months",
    "Best Six Months"
]

for keyword in keywords:

    print("\nSearching:", keyword)

    for page_num in range(len(pdf)):

        text = pdf[page_num].get_text()

        if keyword in text:

            print(
                f"Found on page {page_num+1}"
            )

Searching: Memorial Day
Found on page 65
Found on page 67
Found on page 75
Found on page 78
Found on page 111
Found on page 112

Searching: Midterm
Found on page 12
Found on page 13
Found on page 14
Found on page 18
Found on page 30
Found on page 38
Found on page 40
Found on page 45
Found on page 56
Found on page 65
Found on page 80
Found on page 88
Found on page 92
Found on page 103
Found on page 114
Found on page 116
Found on page 127
Found on page 135
Found on page 137
Found on page 138
Found on page 149
Found on page 175

Searching: Worst Six Months
Found on page 12
Found on page 129
Found on page 130
Found on page 146

Searching: Best Six Months
Found on page 30
Found on page 56
Found on page 64
Found on page 69
Found on page 72
Found on page 75
Found on page 88
Found on page 127
Found on page 130
Found on page 135
Found on page 139
Found on page 146

In [11]:
page = pdf[127]

pix = page.get_pixmap(
    matrix=fitz.Matrix(3,3)
)

pix.save(
    "memorial_day_evidence.png"
)

print("saved")

saved

In [12]:
for page_num in range(len(pdf)):
    text = pdf[page_num].get_text()
    if "Memorial Day" in text:
        print("Found on page:", page_num + 1)

Found on page: 65
Found on page: 67
Found on page: 75
Found on page: 78
Found on page: 111
Found on page: 112

In [15]:
for page_num in [66, 74, 77]:

    page = pdf[page_num]

    pix = page.get_pixmap(
        matrix=fitz.Matrix(3,3)
    )

    pix.save(
        f"page_{page_num+1}.png"
    )

print("Done")

Done

In [ ]:
Worst six months of the year begin with May

This is evidence of bearish sentiment.

    
Memorial Day Week
Dow Down 17 of Last 29
Up 12 Straight 1984-1995

Historical Bias = Bearish


Day After Memorial Day

Dow Up 23 of Last 39
But Down 8 of Last 10

Mixed Signal

In [16]:
week2_evidence = {
    "Evidence": [
        "May begins the Worst Six Months",
        "Midterm Year May return is -0.7%",
        "Memorial Day Week down 17 of last 29 years",
        "Day After Memorial Day down 8 of last 10 years"
    ],

    "Impact": [
        "Bearish",
        "Bearish",
        "Bearish",
        "Slightly Bearish"
    ]
}

week2_evidence

{'Evidence': ['May begins the Worst Six Months',
  'Midterm Year May return is -0.7%',
  'Memorial Day Week down 17 of last 29 years',
  'Day After Memorial Day down 8 of last 10 years'],
 'Impact': ['Bearish', 'Bearish', 'Bearish', 'Slightly Bearish']}

In [17]:
import pandas as pd

evidence_df = pd.DataFrame(week2_evidence)

evidence_df

                                         Evidence            Impact
0                 May begins the Worst Six Months           Bearish
1                Midterm Year May return is -0.7%           Bearish
2      Memorial Day Week down 17 of last 29 years           Bearish
3  Day After Memorial Day down 8 of last 10 years  Slightly Bearish

In [18]:
almanac_agent = {
    "Month": "May",

    "Bias": "Bearish",

    "Confidence": "Medium",

    "Bullish Factors": [
        "Average May return +0.3%",
        "46 up years versus 29 down years"
    ],

    "Bearish Factors": [
        "Midterm Year average return -0.7%",
        "May begins Worst Six Months",
        "Memorial Day Week down 17 of last 29 years",
        "Day After Memorial Day down 8 of last 10 years"
    ],

    "Final Verdict":
        "Bearish"
}

almanac_agent

{'Month': 'May',
 'Bias': 'Bearish',
 'Confidence': 'Medium',
 'Bullish Factors': ['Average May return +0.3%',
  '46 up years versus 29 down years'],
 'Bearish Factors': ['Midterm Year average return -0.7%',
  'May begins Worst Six Months',
  'Memorial Day Week down 17 of last 29 years',
  'Day After Memorial Day down 8 of last 10 years'],
 'Final Verdict': 'Bearish'}

In [19]:
evidence_df.to_csv(
    "week2_almanac_evidence.csv",
    index=False
)

print("Week2 Evidence Saved")

Week2 Evidence Saved

In [20]:
week2_md = """# Week 2 Almanac Agent Output

## Role

R3 – Almanac Lead

---

## Month

May 2026

---

## Almanac Research Summary

According to the Stock Trader's Almanac, May marks the beginning of the Worst Six Months of the year (May–October).

Although May has historically produced a positive average return for the S&P 500, Midterm Election Years have shown weaker performance.

As 2026 is a Midterm Election Year, historical seasonality suggests a cautious outlook.

---

## Bullish Factors

1. S&P 500 average May return: +0.3%

2. S&P 500 recorded 46 up years versus 29 down years

3. NASDAQ average May return: +1.1%

4. Russell 2000 average May return: +1.3%

---

## Bearish Factors

1. Midterm Election Year S&P 500 average May return: -0.7%

2. May begins the Worst Six Months period

3. Memorial Day Week:
   - Dow down 17 of the last 29 years

4. Day After Memorial Day:
   - Dow down 8 of the last 10 years

5. Midterm Election Years historically experience weakness during Q2 and Q3

---

## Key Evidence

| Evidence | Impact |
|-----------|-----------|
| May begins Worst Six Months | Bearish |
| Midterm Year May return -0.7% | Bearish |
| Memorial Day Week down 17 of last 29 years | Bearish |
| Day After Memorial Day down 8 of last 10 years | Slightly Bearish |
| Average May return +0.3% | Bullish |

---

## Confidence

Medium

---

## Final Verdict

Bearish

---

## Recommendation to AI Synthesis Team

Historical seasonality suggests that May 2026 carries elevated downside risk due to:

- Midterm Election Year weakness
- Start of the Worst Six Months period
- Weak Memorial Day Week statistics

The Almanac Agent therefore assigns a Bearish outlook with Medium confidence.
"""

with open(
    "week2_almanac.md",
    "w",
    encoding="utf-8"
) as f:
    f.write(week2_md)

print("week2_almanac.md created successfully")

week2_almanac.md created successfully